@startuml
'
' Resource:  Party
' Source:    Party_4.0.0_oas.yaml
' Generated: 2020-11-18 16:49:56+0100
'
hide circle
hide methods
hide stereotype
show <<Enumeration>> stereotype
skinparam class {
   backgroundColor<<Enumeration>> #E6F5F7
   backgroundColor<<Ref>> #FFFFE0
   backgroundColor<<Pivot>> #FFFFFFF
   backgroundColor #FCF2E3
   backgroundColor<<SubResource>> MistyRose
}

skinparam legend {
   borderRoundCorner 0
   borderColor red
   backgroundColor white
}

'sequence: 6
class Party <extends  \nEntity >  <<SubResource>> {
    href : String
    id : String
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

'sequence: 16
class TaxDefinition <extends  \nExtensible >  {
    id : String
    jurisdictionLevel : String
    jurisdictionName : String
    name : String
    taxType : String
    validFor : TimePeriod
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

'sequence: 25
class ContactMedium <extends  \nEntity >  {
    href : Uri
    id : String
    mediumType : String
    preferred : Boolean
    validFor : TimePeriod
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

'sequence: 32
class CharacteristicRelationship <extends  \nEntity >  <<Ref>> {
    href : Uri
    id : String
    relationshipType : String
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

'sequence: 40
class Characteristic <extends  \nExtensible >  {
    id : String
    name : String [1]
    value : Any [1]
    valueType : String
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

'sequence: 54
class Attachment <extends  \nEntity >  {
    attachmentType : String
    content : Base64
    description : String
    href : Uri
    id : String
    mimeType : String
    name : String
    size : Quantity
    url : Uri
    validFor : TimePeriod
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

'sequence: 65
class PartyCreditProfile <extends  \nEntity >  {
    creditAgencyName : String
    creditAgencyType : String
    href : Uri
    id : String
    ratingReference : String
    ratingScore : Integer32
    validFor : TimePeriod
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

'sequence: 82
class MediumCharacteristic <extends  \nEntity >  {
    city : String
    contactType : String
    country : String
    emailAddress : String
    faxNumber : String
    href : Uri
    id : String
    phoneNumber : String
    postCode : String
    socialNetworkId : String
    stateOrProvince : String
    street1 : String
    street2 : String
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

'sequence: 90
class ExternalReference <extends  \nEntity >  {
    externalReferenceType : String
    href : Uri
    id : String
    name : String
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

'sequence: 99
class RelatedParty <extends  \nEntityRef >  {
    href : Uri
    id : String [1]
    name : String
    role : String
    @baseType : String
    @referredType : String [1]
    @schemaLocation : Uri
    @type : String
}

'sequence: 100
class AttachmentRefOrValue  {
    {field}//                                        //
}

'sequence: 110
class AttachmentRef <extends  \nEntityRef >  <<Ref>> {
    description : String
    href : Uri
    id : String
    name : String
    url : Uri
    @baseType : String
    @referredType : String
    @schemaLocation : Uri
    @type : String
}

'sequence: 119
class TaxExemptionCertificate <extends  \nExtensible >  {
    certificateNumber : String
    id : String
    issuingJurisdiction : String
    reason : String
    validFor : TimePeriod
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

'sequence: 6
'processing edges for Party
'sequence: 122
'rule: General above rule
ContactMedium "0..*" <--* Party : contactMedium

'sequence: 124
'rule: General below rule
Party *-->  "0..*" Characteristic : partyCharacteristic

'sequence: 126
'rule: General below rule
Party *-->  "0..*" TaxExemptionCertificate : taxExemptionCertificate

'sequence: 119
'processing edges for TaxExemptionCertificate
'sequence: 136
'rule: General below rule
TaxExemptionCertificate *-->   AttachmentRefOrValue : attachment

'sequence: 144
'rule: General left rule
PartyCreditProfile "0..*" <-left-* Party : creditRating

'sequence: 146
'rule: General right rule
Party *-right-> "0..*" ExternalReference : externalReference

'sequence: 148
'rule: General above rule - direction: RIGHT
RelatedParty "0..*" <--* Party : relatedParty

'sequence: 25
'processing edges for ContactMedium
'completed processing of edges for ContactMedium
'processing edges for ContactMedium
'sequence: 168
'rule: General left rule
MediumCharacteristic  <-left-* ContactMedium : characteristic

'sequence: 40
'processing edges for Characteristic
'completed processing of edges for Characteristic
'processing edges for Characteristic
'sequence: 172
'rule: General below rule
Characteristic *-->  "0..*" CharacteristicRelationship : characteristicRelationship

'sequence: 100
'processing edges for AttachmentRefOrValue
'completed processing of edges for AttachmentRefOrValue
'processing edges for AttachmentRefOrValue
'sequence: 176
'rule: General below rule
AttachmentRefOrValue --|> Attachment : allOf

'sequence: 178
'rule: General below rule
AttachmentRefOrValue --|> AttachmentRef : allOf

'sequence: 183
'rule: General below rule - either none already or unable to place left / right of currently placed
TaxExemptionCertificate *-->  "0..*" TaxDefinition : taxDefinition



'layout of the core: [Party, ContactMedium, Characteristic, AttachmentRefOrValue, TaxExemptionCertificate] (seq=120)
'finished layout of the core (seq=139)
'y=9 : ContactMedium (10) MediumCharacteristic (9) RelatedParty (10) (seq=186)
'y=10 : PartyCreditProfile (9) Party (10) ExternalReference (11) (seq=187)
'y=11 : Characteristic (10) TaxExemptionCertificate (9) (seq=188)
'y=12 : TaxDefinition (9) CharacteristicRelationship (10) AttachmentRefOrValue (9) (seq=189)
'y=13 : Attachment (9) AttachmentRef (8) (seq=190)
@enduml
