@startuml
'
' Resource:  ProductOffering
' Source:    Product_Catalog_Management_4.1.0_oas.yaml
' Generated: 2020-11-18 16:35:42+0100
'
hide circle
hide methods
hide stereotype
show <<Enumeration>> stereotype
skinparam class {
   backgroundColor<<Enumeration>> #E6F5F7
   backgroundColor<<Ref>> #FFFFE0
   backgroundColor<<Pivot>> #FFFFFFF
   backgroundColor #FCF2E3
   backgroundColor<<SubResource>> MistyRose
}

skinparam legend {
   borderRoundCorner 0
   borderColor red
   backgroundColor white
}

'sequence: 15
class ProductOffering <extends  \nExtensible \nAddressable >  <<Pivot>> {
    description : String
    href : String
    id : String
    isBundle : Boolean
    isSellable : Boolean
    lastUpdate : DateTime
    lifecycleStatus : String
    name : String
    statusReason : String
    validFor : TimePeriod
    version : String
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

'sequence: 23
class AgreementRef <extends  \nEntityRef >  <<Ref>> {
    href : Uri
    id : String
    name : String
    @baseType : String
    @referredType : String
    @schemaLocation : Uri
    @type : String
}

'sequence: 32
class CategoryRef <extends  \nEntityRef >  <<Ref>> {
    href : Uri
    id : String
    name : String
    version : String
    @baseType : String
    @referredType : String
    @schemaLocation : Uri
    @type : String
}

'sequence: 46
class Attachment <extends  \nEntity >  {
    attachmentType : String
    content : Base64
    description : String
    href : Uri
    id : String
    mimeType : String
    name : String
    size : Quantity
    url : Uri
    validFor : TimePeriod
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

'sequence: 54
class ChannelRef <extends  \nEntityRef >  <<Ref>> {
    href : Uri
    id : String
    name : String
    @baseType : String
    @referredType : String
    @schemaLocation : Uri
    @type : String
}

'sequence: 62
class PlaceRef <extends  \nEntityRef >  <<Ref>> {
    href : Uri
    id : String
    name : String
    @baseType : String
    @referredType : String
    @schemaLocation : Uri
    @type : String
}

'sequence: 65
class TargetProductSchema  {
    @schemaLocation : Uri [1]
    @type : String [1]
}

'sequence: 74
class ServiceCandidateRef <extends  \nEntityRef >  <<Ref>> {
    href : Uri
    id : String
    name : String
    version : String
    @baseType : String
    @referredType : String
    @schemaLocation : Uri
    @type : String
}

'sequence: 82
class ProductOfferingTerm <extends  \nExtensible >  {
    description : String
    duration : Quantity
    name : String
    validFor : TimePeriod
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

'sequence: 93
class ProductSpecificationCharacteristicValueUse <extends  \nExtensible >  {
    description : String
    id : String
    maxCardinality : Integer
    minCardinality : Integer
    name : String
    validFor : TimePeriod
    valueType : String
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

'sequence: 100
class BundledProductOfferingOption <extends  \nExtensible >  {
    numberRelOfferDefault : Integer
    numberRelOfferLowerLimit : Integer
    numberRelOfferUpperLimit : Integer
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

'sequence: 108
class ProductOfferingPriceRef <extends  \nEntityRef >  <<Ref>> {
    href : Uri
    id : String
    name : String
    @baseType : String
    @referredType : String
    @schemaLocation : Uri
    @type : String
}

'sequence: 116
class MarketSegmentRef <extends  \nEntity >  <<Ref>> {
    href : String
    id : String
    name : String
    @baseType : String
    @referredType : String
    @schemaLocation : Uri
    @type : String
}

'sequence: 125
class ResourceCandidateRef <extends  \nEntityRef >  <<Ref>> {
    href : Uri
    id : String
    name : String
    version : String
    @baseType : String
    @referredType : String
    @schemaLocation : Uri
    @type : String
}

'sequence: 133
class BundledProductOffering <extends  \nExtensible >  {
    href : String
    id : String
    lifecycleStatus : String
    name : String
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

'sequence: 141
class SLARef <extends  \nEntity >  <<Ref>> {
    href : String
    id : String
    name : String
    @baseType : String
    @referredType : String
    @schemaLocation : Uri
    @type : String
}

'sequence: 142
class AttachmentRefOrValue  {
    {field}//                                        //
}

'sequence: 151
class ProductSpecificationRef <extends  \nEntityRef >  <<Ref>> {
    href : Uri
    id : String
    name : String
    version : String
    @baseType : String
    @referredType : String
    @schemaLocation : Uri
    @type : String
}

'sequence: 161
class AttachmentRef <extends  \nEntityRef >  <<Ref>> {
    description : String
    href : Uri
    id : String
    name : String
    url : Uri
    @baseType : String
    @referredType : String
    @schemaLocation : Uri
    @type : String
}

'sequence: 174
class CharacteristicValueSpecification <extends  \nExtensible >  {
    isDefault : Boolean
    rangeInterval : String
    regex : String
    unitOfMeasure : String
    validFor : TimePeriod
    value : Any
    valueFrom : Integer
    valueTo : Integer
    valueType : String
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

'sequence: 15
'processing edges for ProductOffering
'sequence: 177
'rule: circle rule :: effectiveCircle = ProductOffering ProductSpecificationRef ProductSpecificationCharacteristicValueUse ProductOffering - special case - threePart=true multiple=false - place [BELOW, RIGHT] - default to BELOW
ProductOffering *-->   ProductSpecificationRef : productSpecification

'sequence: 179
'rule: circle rule :: effectiveCircle = ProductOffering ProductSpecificationRef ProductSpecificationCharacteristicValueUse ProductOffering - special case - threePart=true multiple=false - place [BELOW, RIGHT] - default to RIGHT
ProductSpecificationRef  <-left-* ProductSpecificationCharacteristicValueUse : productSpecification

'sequence: 181
'rule: circle rule :: effectiveCircle = ProductOffering ProductSpecificationRef ProductSpecificationCharacteristicValueUse ProductOffering - special case - threePart=true multiple=false - place [BELOW, RIGHT] - default to RIGHT - override default direction - now ABOVE
ProductOffering *-->  "0..*" ProductSpecificationCharacteristicValueUse : prodSpecCharValueUse

'sequence: 185
'rule: General below rule - either none already or unable to place left / right of currently placed
ProductOffering *-->  "0..*" BundledProductOffering : bundledProductOffering

'sequence: 187
'rule: General below rule - either none already or unable to place left / right of currently placed
ProductOffering *-->  "0..*" AttachmentRefOrValue : attachment

'sequence: 205
'rule: General left rule
ServiceCandidateRef  <-left-* ProductOffering : serviceCandidate

'sequence: 207
'rule: General right rule
ProductOffering *-right-> "0..*" ProductOfferingTerm : productOfferingTerm

'sequence: 209
'rule: General above rule
MarketSegmentRef "0..*" <--* ProductOffering : marketSegment

'sequence: 211
'rule: General above rule
ProductOfferingPriceRef "0..*" <--* ProductOffering : productOfferingPrice

'sequence: 213
'rule: General above rule
CategoryRef "0..*" <--* ProductOffering : category

'sequence: 215
'rule: General above rule
AgreementRef "0..*" <--* ProductOffering : agreement

'sequence: 217
'rule: General above rule
ResourceCandidateRef  <--* ProductOffering : resourceCandidate

'sequence: 219
'rule: General above rule
PlaceRef "0..*" <--* ProductOffering : place

'sequence: 221
'rule: General below rule - either none already or unable to place left / right of currently placed
ProductOffering *-->  "0..*" ChannelRef : channel

'sequence: 223
'rule: General below rule - either none already or unable to place left / right of currently placed
ProductOffering *-->   SLARef : serviceLevelAgreement

'sequence: 133
'processing edges for BundledProductOffering
'completed processing of edges for BundledProductOffering
'processing edges for BundledProductOffering
'sequence: 257
'rule: General below rule
BundledProductOffering *-->   BundledProductOfferingOption : bundledProductOfferingOption

'sequence: 151
'processing edges for ProductSpecificationRef
'completed processing of edges for ProductSpecificationRef
'processing edges for ProductSpecificationRef
'sequence: 261
'rule: General below rule
ProductSpecificationRef *-->   TargetProductSchema : targetProductSchema

'sequence: 142
'processing edges for AttachmentRefOrValue
'completed processing of edges for AttachmentRefOrValue
'processing edges for AttachmentRefOrValue
'sequence: 265
'rule: General below rule
AttachmentRefOrValue --|> Attachment : allOf

'sequence: 267
'rule: General below rule
AttachmentRefOrValue --|> AttachmentRef : allOf

'sequence: 93
'processing edges for ProductSpecificationCharacteristicValueUse
' finished with placeWithPlaced P02-3
'completed processing of edges for ProductSpecificationCharacteristicValueUse
'processing edges for ProductSpecificationCharacteristicValueUse
' finished with placeWithPlaced P02-3
'sequence: 272
'rule: General below rule
ProductSpecificationCharacteristicValueUse *-->  "0..*" CharacteristicValueSpecification : productSpecCharacteristicValue



'layout of the core: [ProductOffering, ProductSpecificationCharacteristicValueUse, BundledProductOffering, AttachmentRefOrValue, ProductSpecificationRef] (seq=175)
'finished layout of the core (seq=199)
'y=9 : CategoryRef (10) AgreementRef (10) PlaceRef (10) MarketSegmentRef (10) ProductOfferingPriceRef (10) ResourceCandidateRef (10) (seq=275)
'y=10 : ServiceCandidateRef (9) ProductOfferingTerm (11) ProductOffering (10) (seq=276)
'y=11 : ChannelRef (10) ProductSpecificationCharacteristicValueUse (11) BundledProductOffering (10) SLARef (9) AttachmentRefOrValue (9) ProductSpecificationRef (10) (seq=277)
'y=12 : Attachment (9) TargetProductSchema (10) BundledProductOfferingOption (10) AttachmentRef (8) CharacteristicValueSpecification (11) (seq=278)
@enduml