@startuml
'
' Resource:  CancelProductOrder
' Source:    Product_Ordering_4.0.0_oas.yaml
' Generated: 2020-11-18 23:09:09+0100
'
hide circle
hide methods
hide stereotype
show <<Enumeration>> stereotype
skinparam class {
   backgroundColor<<Enumeration>> #E6F5F7
   backgroundColor<<Ref>> #FFFFE0
   backgroundColor<<Pivot>> #FFFFFFF
   backgroundColor #FCF2E3
   backgroundColor<<SubResource>> MistyRose
}

skinparam legend {
   borderRoundCorner 0
   borderColor red
   backgroundColor white
}

'sequence: 1
class CancelProductOrder  <<Pivot>> {
    {field}//                                        //
}

'sequence: 9
class ProductOrderRef <extends  \nEntityRef >  <<Ref>> {
    href : Uri
    id : String
    name : String
    @baseType : String
    @referredType : String
    @schemaLocation : Uri
    @type : String
}

'sequence: 19
class CancelOrder <extends  \nEntity >  {
    cancellationReason : String
    effectiveCancellationDate : DateTime
    href : String
    id : String
    requestedCancellationDate : DateTime
    state : TaskStateType
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

'sequence: 20
class TaskStateType <<Enumeration>> {
    inProgress
    terminatedWithError
    accepted
    done
}

'sequence: 1
'processing edges for CancelProductOrder
'sequence: 23
'rule: General below rule
CancelProductOrder --|> CancelOrder : allOf

'sequence: 19
'processing edges for CancelOrder
'sequence: 27
CancelOrder -right[hidden]-> TaskStateType

'sequence: 33
'rule: General below rule - either none already or unable to place left / right of currently placed
CancelProductOrder *-->  "1" ProductOrderRef : productOrder



'layout of the core: [CancelProductOrder, CancelOrder] (seq=21)
'finished layout of the core (seq=30)
'y=10 : CancelProductOrder (10) (seq=41)
'y=11 : ProductOrderRef (10) TaskStateType (11) CancelOrder (10) (seq=42)
@enduml