@startuml
'
' Resource:  ProductSpecificationCharacteristic
' Source:    Product_Catalog_Management_4.1.0_oas.yaml
' Generated: 2020-11-14 11:54:23+0100
'
hide circle
hide methods
hide stereotype
show <<Enumeration>> stereotype
skinparam class {
   backgroundColor<<Enumeration>> #E6F5F7
   backgroundColor<<Ref>> #FFFFE0
   backgroundColor<<Pivot>> #FFFFFFF
   backgroundColor #FCF2E3
   backgroundColor<<SubResource>> MistyRose
}

skinparam legend {
   borderRoundCorner 0
   borderColor red
   backgroundColor white
}

'sequence: 1
class ProductSpecificationCharacteristic  <<SubResource>> {
    {field}//                                        //
}

'sequence: 11
class ProductSpecificationCharacteristicRelationship <extends  \nExtensible >  <<Ref>> {
    charSpecSeq : Integer
    href : String
    id : String
    name : String
    relationshipType : String
    validFor : TimePeriod
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

'sequence: 27
class CharacteristicSpecificationBase <extends  \nExtensible >  {
    configurable : Boolean
    description : String
    extensible : Boolean
    id : String
    isUnique : Boolean
    maxCardinality : Integer
    minCardinality : Integer
    name : String
    regex : String
    validFor : TimePeriod
    valueType : String
    @baseType : String
    @schemaLocation : Uri
    @type : String
    @valueSchemaLocation : String
}

'sequence: 40
class CharacteristicValueSpecification <extends  \nExtensible >  {
    isDefault : Boolean
    rangeInterval : String
    regex : String
    unitOfMeasure : String
    validFor : TimePeriod
    value : Any
    valueFrom : Integer
    valueTo : Integer
    valueType : String
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

'sequence: 1
'processing edges for ProductSpecificationCharacteristic
'completed processing of edges for ProductSpecificationCharacteristic
'processing edges for ProductSpecificationCharacteristic
'sequence: 46
'rule: General right rule
ProductSpecificationCharacteristic *-right-> "0..*" ProductSpecificationCharacteristicRelationship : productSpecCharRelationship

'sequence: 48
'rule: General above rule
CharacteristicSpecificationBase <|-- ProductSpecificationCharacteristic : allOf

'sequence: 50
'rule: General below rule
ProductSpecificationCharacteristic *-->  "0..*" CharacteristicValueSpecification : productSpecCharacteristicValue



'layout of the core: [ProductSpecificationCharacteristic] (seq=41)
'finished layout of the core (seq=44)
'y=9 : CharacteristicSpecificationBase (10) (seq=59)
'y=10 : ProductSpecificationCharacteristicRelationship (11) ProductSpecificationCharacteristic (10) (seq=60)
'y=11 : CharacteristicValueSpecification (10) (seq=61)
@enduml