@startuml
'
' Resource:  Product
' Source:    Product_Ordering_4.0.0_oas.yaml
' Generated: 2020-11-18 23:09:09+0100
'
hide circle
hide methods
hide stereotype
show <<Enumeration>> stereotype
skinparam class {
   backgroundColor<<Enumeration>> #E6F5F7
   backgroundColor<<Ref>> #FFFFE0
   backgroundColor<<Pivot>> #FFFFFFF
   backgroundColor #FCF2E3
   backgroundColor<<SubResource>> MistyRose
}

skinparam legend {
   borderRoundCorner 0
   borderColor red
   backgroundColor white
}

'sequence: 17
class Product <extends  \nEntity >  <<SubResource>> {
    description : String
    href : String
    id : String
    isBundle : Boolean
    isCustomerVisible : Boolean
    name : String
    orderDate : DateTime
    product : ProductRefOrValue [0..*]
    productSerialNumber : String
    randomAtt : String
    startDate : DateTime
    status : ProductStatusType
    terminationDate : DateTime
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

'sequence: 18
class ProductStatusType <<Enumeration>> {
    pendingTerminate
    created
    cancelled
    active
    pendingActive
    aborted 
    terminated
    suspended
}

'sequence: 30
class RelatedProductOrderItem <extends  \nEntity >  {
    href : Uri
    id : String
    orderItemAction : String
    orderItemId : String [1]
    productOrderHref : String
    productOrderId : String [1]
    role : String
    @baseType : String
    @referredType : String
    @schemaLocation : Uri
    @type : String
}

'sequence: 38
class ProductOfferingRef <extends  \nEntityRef >  <<Ref>> {
    href : Uri
    id : String
    name : String
    @baseType : String
    @referredType : String
    @schemaLocation : Uri
    @type : String
}

'sequence: 45
class CharacteristicRelationship <extends  \nEntity >  <<Ref>> {
    href : Uri
    id : String
    relationshipType : String
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

'sequence: 54
class BillingAccountRef <extends  \nEntity >  <<Ref>> {
    href : String
    id : String
    name : String
    ratingType : String
    @baseType : String
    @referredType : String
    @schemaLocation : Uri
    @type : String
}

'sequence: 62
class Characteristic <extends  \nExtensible >  {
    id : String
    name : String [1]
    value : Any [1]
    valueType : String
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

'sequence: 73
class ProductPrice <extends  \nEntity >  {
    description : String
    href : Uri
    id : String
    name : String
    priceType : String [1]
    recurringChargePeriod : String
    unitOfMeasure : String
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

'sequence: 81
class PlaceRef <extends  \nEntityRef >  <<Ref>> {
    href : Uri
    id : String
    name : String
    @baseType : String
    @referredType : String
    @schemaLocation : Uri
    @type : String
}

'sequence: 84
class TargetProductSchema  {
    @schemaLocation : Uri [1]
    @type : String [1]
}

'sequence: 97
class PriceAlteration <extends  \nEntity >  {
    applicationDuration : Integer
    description : String
    href : Uri
    id : String
    name : String
    priceType : String [1]
    priority : Integer
    recurringChargePeriod : String
    unitOfMeasure : String
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

'sequence: 105
class ProductOfferingPriceRef <extends  \nEntityRef >  <<Ref>> {
    href : Uri
    id : String
    name : String
    @baseType : String
    @referredType : String
    @schemaLocation : Uri
    @type : String
}

'sequence: 113
class ProductRelationship <extends  \nEntity >  <<Ref>> {
    href : Uri
    id : String
    product : ProductRefOrValue [1]
    relationshipType : String [1]
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

'sequence: 123
class Price <extends  \nEntity >  {
    dutyFreeAmount : Money
    href : Uri
    id : String
    percentage : Float
    taxIncludedAmount : Money
    taxRate : Float
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

'sequence: 132
class AgreementItemRef <extends  \nEntityRef >  <<Ref>> {
    agreementItemId : String
    href : Uri
    id : String
    name : String
    @baseType : String
    @referredType : String
    @schemaLocation : Uri
    @type : String
}

'sequence: 134
class RelatedPlaceRefOrValue  {
    role : String [1]
}

'sequence: 143
class RelatedParty <extends  \nEntityRef >  {
    href : Uri
    id : String [1]
    name : String
    role : String
    @baseType : String
    @referredType : String [1]
    @schemaLocation : Uri
    @type : String
}

'sequence: 151
class ResourceRef <extends  \nEntityRef >  <<Ref>> {
    href : Uri
    id : String
    name : String
    @baseType : String
    @referredType : String
    @schemaLocation : Uri
    @type : String
}

'sequence: 161
class ProductTerm <extends  \nEntity >  {
    description : String
    duration : Quantity
    href : Uri
    id : String
    name : String
    validFor : TimePeriod
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

'sequence: 169
class ServiceRef <extends  \nEntityRef >  <<Ref>> {
    href : Uri
    id : String
    name : String
    @baseType : String
    @referredType : String
    @schemaLocation : Uri
    @type : String
}

'sequence: 178
class ProductSpecificationRef <extends  \nEntityRef >  <<Ref>> {
    href : Uri
    id : String
    name : String
    version : String
    @baseType : String
    @referredType : String
    @schemaLocation : Uri
    @type : String
}

'sequence: 185
class Place <extends  \nEntity >  {
    href : String
    id : String
    name : String
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

'sequence: 17
'processing edges for Product
'sequence: 188
'rule: circle rule :: effectiveCircle = Product BillingAccountRef ProductPrice Product - free to LEFT - place [LEFT, BELOW, RIGHT] - default to LEFT
BillingAccountRef  <-left-* Product : billingAccount

'sequence: 190
'rule: circle rule :: effectiveCircle = Product BillingAccountRef ProductPrice Product - free to LEFT - place [LEFT, BELOW, RIGHT] - default to BELOW
BillingAccountRef  <--* ProductPrice : billingAccount

'sequence: 192
'rule: circle rule :: effectiveCircle = Product BillingAccountRef ProductPrice Product - free to LEFT - place [LEFT, BELOW, RIGHT] - default to RIGHT - override default direction - now ABOVE
Product *-->  "0..*" ProductPrice : productPrice

'sequence: 196
Product -right[hidden]-> ProductStatusType

'sequence: 198
'rule: General above rule
Characteristic "0..*" <--* Product : productCharacteristic

'sequence: 200
'rule: General below rule - either none already or unable to place left / right of currently placed
Product *-->  "0..*" RelatedPlaceRefOrValue : place

'sequence: 202
'rule: General below rule - either none already or unable to place left / right of currently placed
Product *-->   ProductSpecificationRef : productSpecification

'sequence: 97
'processing edges for PriceAlteration
'sequence: 206
'rule: circle rule :: effectiveCircle = ProductPrice Price PriceAlteration ProductOfferingPriceRef ProductPrice - free to LEFT - place [LEFT, BELOW, RIGHT] - default to LEFT
Price "1" <-left-* ProductPrice : price

'sequence: 208
'rule: forceLeftRight
ProductPrice <-left[hidden]- ProductSpecificationRef

'sequence: 210
'rule: circle rule :: effectiveCircle = ProductPrice Price PriceAlteration ProductOfferingPriceRef ProductPrice - free to LEFT - place [LEFT, BELOW, RIGHT] - default to BELOW
Price "1" <--* PriceAlteration : price

'sequence: 212
'rule: circle rule :: effectiveCircle = ProductPrice Price PriceAlteration ProductOfferingPriceRef ProductPrice - free to LEFT - place [LEFT, BELOW, RIGHT] - default to RIGHT
PriceAlteration *-right->  ProductOfferingPriceRef : productOfferingPrice

'sequence: 214
'rule: circle rule :: effectiveCircle = ProductPrice Price PriceAlteration ProductOfferingPriceRef ProductPrice - free to LEFT - place [LEFT, BELOW, RIGHT] - default to RIGHT - override default direction - now ABOVE
ProductPrice *-->   ProductOfferingPriceRef : productOfferingPrice

'sequence: 73
'processing edges for ProductPrice
'sequence: 224
'rule: P02-2
ProductPrice *-->  "0..*" PriceAlteration : productPriceAlteration

'sequence: 241
'rule: General above rule - direction: RIGHT
RelatedProductOrderItem "0..*" <--* Product : productOrderItem

'sequence: 243
'rule: General above rule - direction: RIGHT
ProductOfferingRef  <--* Product : productOffering

'sequence: 245
'rule: General above rule - direction: RIGHT
AgreementItemRef "0..*" <--* Product : agreement

'sequence: 247
'rule: General above rule - direction: RIGHT
RelatedParty "0..*" <--* Product : relatedParty

'sequence: 249
'rule: General above rule - direction: RIGHT
ProductTerm "0..*" <--* Product : productTerm

'sequence: 251
'rule: General below rule - either none already or unable to place left / right of currently placed
Product *-->  "0..*" ProductRelationship : productRelationship

'sequence: 253
'rule: General below rule - either none already or unable to place left / right of currently placed
Product *-->  "0..*" ResourceRef : realizingResource

'sequence: 255
'rule: General below rule - either none already or unable to place left / right of currently placed
Product *-->  "0..*" ServiceRef : realizingService

'sequence: 62
'processing edges for Characteristic
'completed processing of edges for Characteristic
'processing edges for Characteristic
'sequence: 289
'rule: General right rule
Characteristic *-right-> "0..*" CharacteristicRelationship : characteristicRelationship

'sequence: 178
'processing edges for ProductSpecificationRef
'completed processing of edges for ProductSpecificationRef
'processing edges for ProductSpecificationRef
'sequence: 293
'rule: General below rule
ProductSpecificationRef *-->   TargetProductSchema : targetProductSchema

'sequence: 134
'processing edges for RelatedPlaceRefOrValue
'completed processing of edges for RelatedPlaceRefOrValue
'processing edges for RelatedPlaceRefOrValue
'sequence: 301
'rule: General below rule
RelatedPlaceRefOrValue --|> PlaceRef : allOf

'sequence: 303
'rule: General below rule
RelatedPlaceRefOrValue --|> Place : allOf



'layout of the core: [Product, PriceAlteration, Characteristic, RelatedPlaceRefOrValue, ProductPrice, ProductSpecificationRef] (seq=186)
'finished layout of the core (seq=233)
'y=9 : RelatedProductOrderItem (10) ProductOfferingRef (10) CharacteristicRelationship (11) Characteristic (10) AgreementItemRef (10) RelatedParty (10) ProductTerm (10) (seq=312)
'y=10 : BillingAccountRef (9) Product (10) ProductStatusType (11) (seq=313)
'y=11 : ProductPrice (9) Price (8) ProductRelationship (10) RelatedPlaceRefOrValue (10) ResourceRef (9) ServiceRef (8) ProductSpecificationRef (9) (seq=314)
'y=12 : PlaceRef (10) PriceAlteration (8) TargetProductSchema (9) ProductOfferingPriceRef (9) Place (9) (seq=315)
@enduml